# Sample tracker configuration
spring:
  config:
    activate:
      on-profile: "dev"
build:
  version: "3.0-dev"
details:
  name: "Tracker"
  description: "Gym Service is a simple api to manage exercise plans"
  author: "{cipher}588f1cc91622008f0e2d818f9b73e35e5468b4a0ef7e25cc8a95dee3355ff89f9c5b3591b03d57494bbea070c9af76cc"
