# Sample tracker configuration
spring:
  config:
    activate:
      on-profile: "prod"
build:
  version: "2.0-prod"
details:
  name: "Tracker"
  description: "Tracker is a simple application to track the user exercise actitvity"
  author: "{cipher}588f1cc91622008f0e2d818f9b73e35e5468b4a0ef7e25cc8a95dee3355ff89f9c5b3591b03d57494bbea070c9af76cc"
